#---------------------------------#
#   master branch configuration   #
#---------------------------------#
-
  branches:
    only:
      - master

  version: 7.0.{build}

  # Assembly versioning
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_file_version: "7.0.0.{build}"
    assembly_informational_version: "7.0.0.{build}"
    assembly_version: "7.0.0.{build}"

  artifacts:
    - path: .\VsExt.AutoShelve\bin\$(configuration)\TfsAutoShelve2019v7.0.vsix
      name: TfsAutoShelve2019v7.0.vsix

  build:
    project: VsExt.AutoShelve\VsExt.AutoShelve.csproj   # path to Visual Studio solution or project
    verbosity: minimal # MSBuild verbosity level quiet|minimal|normal|detailed

  configuration: Package
  deploy: off 
  os: Visual Studio 2019 # http://www.appveyor.com/docs/installed-software
  platform: Any CPU
  test: off


#---------------------------------#
#   2017 branch configuration     #
#---------------------------------#
-
  branches:
    only:
      - 2017

  version: 6.2.{build}

  # Assembly versioning
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_file_version: "6.2.0.{build}"
    assembly_informational_version: "6.2.0.{build}"
    assembly_version: "6.2.0.{build}"

  artifacts:
    - path: .\VsExt.AutoShelve\bin\$(configuration)\TfsAutoShelve2017v6.2.vsix
      name: TfsAutoShelve2017v6.2.vsix

  build:
    project: VsExt.AutoShelve\VsExt.AutoShelve.csproj   # path to Visual Studio solution or project
    verbosity: minimal # MSBuild verbosity level quiet|minimal|normal|detailed

  configuration: Package
  deploy: off 
  os: Visual Studio 2017 # http://www.appveyor.com/docs/installed-software
  platform: Any CPU
  test: off

#---------------------------------#
#   2015 branch configuration     #
#---------------------------------#
-
  branches:
    only:
      - 2015

  version: 5.4.{build}

  # Assembly versioning
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_file_version: "5.4.0.{build}"
    assembly_informational_version: "5.4.0.{build}"
    assembly_version: "5.4.0.{build}"

  artifacts:
    - path: .\VsExt.AutoShelve\bin\$(configuration)\TfsAutoShelve2015v5.4.vsix
      name: TfsAutoShelve2015v5.4.vsix

  build:
    project: VsExt.AutoShelve\VsExt.AutoShelve.csproj   # path to Visual Studio solution or project
    verbosity: minimal # MSBuild verbosity level quiet|minimal|normal|detailed

  configuration: Package
  deploy: off 
  os: Visual Studio 2015 # http://www.appveyor.com/docs/installed-software
  platform: Any CPU
  test: off

#---------------------------------#
#    2013 branch configuration    #
#---------------------------------#
-
  branches:
    only:
      - 2013

  version: 4.3.{build}

  # Assembly versioning
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_file_version: "4.3.0.{build}"
    assembly_informational_version: "4.3.0.{build}"
    assembly_version: "4.3.0.{build}"

  artifacts:
    - path: .\VsExt.AutoShelve\bin\$(configuration)\TfsAutoShelve2013v4.3.vsix
      name: TfsAutoShelve2013v4.3.vsix

  build:
    project: VsExt.AutoShelve\VsExt.AutoShelve.csproj   # path to Visual Studio solution or project
    verbosity: minimal # MSBuild verbosity level quiet|minimal|normal|detailed

  configuration: Package
  deploy: off 
  os: Visual Studio 2015 # http://www.appveyor.com/docs/installed-software
  platform: Any CPU
  test: off